rvm:
  - jruby-9.2.7.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-9.2.7.0
    - rvm: jruby-head

before_script:
  - unset JRUBY_OPTS

script: rake

addons:
  apt:
    packages:
      - haveged
