rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - rbx-2
before_install: gem install bundler --no-document
before_script: rake compile
script: rake test
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
