jobs:
- job: macOS
  pool:
    vmImage: 'macos-10.13'
  steps:
  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'
  - script: rake
    displayName: 'rake'
